coursework-cbsd/deltaspike-beanmanagerprovider/src/main/java/org/jboss/as/quickstarts/deltaspike/beanmanagerprovider/model/AuditContact.java
/*
 * JBoss, Home of Professional Open Source
 * Copyright 2014, Red Hat, Inc. and/or its affiliates, and individual
 * contributors by the @authors tag. See the copyright.txt in the
 * distribution for a full listing of individual contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jboss.as.quickstarts.deltaspike.beanmanagerprovider.model;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * @author <a href="mailto:benevides@redhat.com">Rafael Benevides</a>
 * 
 */
@Entity
@Table(name = "AuditContact")
public class AuditContact {

    @Id
    @GeneratedValue
    private Long id;

    private String contactEmail;

    private String contactName;

    private String contactPhone;

    @Enumerated(EnumType.STRING)
    private OPERATION operation;

    @Temporal(TemporalType.TIMESTAMP)
    private Date dateTime = new Date();

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public OPERATION getOperation() {
        return operation;
    }

    public void setOperation(OPERATION operation) {
        this.operation = operation;
    }

    public void setContactEmail(String contactEmail) {
        this.contactEmail = contactEmail;
    }

    public String getContactEmail() {
        return contactEmail;
    }

    public Date getDateTime() {
        return dateTime;
    }

    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }

    public String getContactName() {
        return contactName;
    }

    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    public String getContactPhone() {
        return contactPhone;
    }

    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((id == null) ? 0 : id.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        AuditContact other = (AuditContact) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        } else if (!id.equals(other.id))
            return false;
        return true;
    }

}

coursework-cbsd/deltaspike-beanmanagerprovider/src/main/java/org/jboss/as/quickstarts/deltaspike/beanmanagerprovider/model/Contact.java
/*
 * JBoss, Home of Professional Open Source
 * Copyright 2014, Red Hat, Inc. and/or its affiliates, and individual
 * contributors by the @authors tag. See the copyright.txt in the
 * distribution for a full listing of individual contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jboss.as.quickstarts.deltaspike.beanmanagerprovider.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.Digits;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotEmpty;
import org.jboss.as.quickstarts.deltaspike.beanmanagerprovider.persistence.AuditContactListener;

/**
 * @author <a href="mailto:benevides@redhat.com">Rafael Benevides</a>
 * 
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "Contact", uniqueConstraints = @UniqueConstraint(columnNames = "email"))
// Here we register the AuditContactListener class as the listener to entity events
@EntityListeners(AuditContactListener.class)
public class Contact implements Serializable {

    @Id
    @GeneratedValue
    private Long id;

    @NotNull
    @Size(min = 1, max = 25)
    @Pattern(regexp = "[A-Za-z ]*", message = "must contain only letters and spaces")
    private String name;

    @NotNull
    @NotEmpty
    @Email
    private String email;

    @NotNull
    @Size(min = 10, max = 12)
    @Digits(fraction = 0, integer = 12)
    @Column(name = "phone_number")
    private String phoneNumber;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((id == null) ? 0 : id.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Contact other = (Contact) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        } else if (!id.equals(other.id))
            return false;
        return true;
    }

}

coursework-cbsd/deltaspike-beanmanagerprovider/src/main/java/org/jboss/as/quickstarts/deltaspike/beanmanagerprovider/model/OPERATION.java
/*
 * JBoss, Home of Professional Open Source
 * Copyright 2014, Red Hat, Inc. and/or its affiliates, and individual
 * contributors by the @authors tag. See the copyright.txt in the
 * distribution for a full listing of individual contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jboss.as.quickstarts.deltaspike.beanmanagerprovider.model;

/**
 * Database operations type
 * 
 * @author <a href="mailto:benevides@redhat.com">Rafael Benevides</a>
 *
 */
public enum OPERATION {
    
    INSERT,
    UPDATE,
    DELETE

}

coursework-cbsd/deltaspike-beanmanagerprovider/src/main/java/org/jboss/as/quickstarts/deltaspike/beanmanagerprovider/controller/ContactController.java
/*
 * JBoss, Home of Professional Open Source
 * Copyright 2014, Red Hat, Inc. and/or its affiliates, and individual
 * contributors by the @authors tag. See the copyright.txt in the
 * distribution for a full listing of individual contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jboss.as.quickstarts.deltaspike.beanmanagerprovider.controller;

import java.io.Serializable;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.enterprise.context.Conversation;
import javax.enterprise.context.ConversationScoped;
import javax.enterprise.event.Observes;
import javax.enterprise.inject.Model;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import org.jboss.as.quickstarts.deltaspike.beanmanagerprovider.model.AuditContact;
import org.jboss.as.quickstarts.deltaspike.beanmanagerprovider.model.Contact;
import org.jboss.as.quickstarts.deltaspike.beanmanagerprovider.persistence.AuditRepository;
import org.jboss.as.quickstarts.deltaspike.beanmanagerprovider.persistence.ContactRepository;

/**
 * 
 * This class uses {@link ConversationScoped} and {@link Named} instead of {@link Model} because it holds the managed
 * {@link Contact} entity instance accross the requests.
 * 
 * @author <a href="mailto:benevides@redhat.com">Rafael Benevides</a>
 * 
 */
@Named
@ConversationScoped
public class ContactController implements Serializable {

    private static final long serialVersionUID = 1L;

    @Inject
    private FacesContext facesContext;

    @Inject
    private ContactRepository contactRepository;

    @Inject
    private AuditRepository auditRepository;

    @Inject
    private Conversation conversation;

    private Contact contact;

    private List<Contact> allContacts;

    // return the managed entity instance
    public Contact getContact() {
        return contact;
    }

    public void save() {
        // Define the faces message based on the entity state
        String msg = isContactManaged() ? "Contact updated" : "New Contact added";
        try {
            contactRepository.persist(contact);
        } catch (Exception e) {
            // discard the conversation (and the entity manager) on any exception
            conversation.end();
            // reset the entity Id
            contact.setId(null);
            msg = "Can't create contact: " + e.getMessage();
        }
        // add the message to be showed on the jsf page
        facesContext.addMessage(null, new FacesMessage(msg));
    }

    public void remove(Contact contact) {
        contactRepository.remove(contact);
        facesContext.addMessage(null, new FacesMessage("Contact Removed"));
        this.contact = new Contact();
    }

    // select an instance from the table to edition
    public void selectForEdit(Contact contact) {
        this.contact = contact;
    }

    /*
     * This method will promote the conversation when this component is constructed through the {@link PostConstruct} annotation
     * This will also create a new entity to be managed/edited and get the list of all contacts previously persisted.
     */
    @PostConstruct
    public void newContact() {
        if (conversation.isTransient()) {
            conversation.begin();
        }
        contact = new Contact();
        allContacts = contactRepository.getAllContacts();
    }

    /*
     * Updates the Contact list when a event on Contact was fired. The Events are produced by {@link ContactRepository}
     */
    public void readAllContacts(@Observes Contact contact) {
        allContacts = contactRepository.getAllContacts();
    }

    // Return the conversation number to be used on the page footer
    public String getConversationNumber() {
        return "Conversation Id: " + (conversation.getId() == null ? "conversation transient" : conversation.getId());
    }

    // Return the information to be used on *All Contacts* table.
    public List<Contact> getAllContacts() {
        return allContacts;
    }

    // Return the information to be used on *Audit Records* table
    public List<AuditContact> getAuditRecords() {
        return auditRepository.getAllAuditRecords();
    }

    public boolean isContactManaged() {
        return contact.getId() != null;
    }

}

coursework-cbsd/deltaspike-beanmanagerprovider/src/main/webapp/contactsCRUD.xhtml
<!--
    JBoss, Home of Professional Open Source
    Copyright 2014, Red Hat, Inc. and/or its affiliates, and individual
    contributors by the @authors tag. See the copyright.txt in the
    distribution for a full listing of individual contributors.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" 
    xmlns:h="http://java.sun.com/jsf/html" 
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets" 
    xmlns:jdf="http://java.sun.com/jsf/composite/jdf">
    <!-- The  http://java.sun.com/jsf/composite/jdf uses the {webroot}/resources/jdf composite components -->
<ui:composition template="/template.xhtml">
    <ui:define name="pageTitle">Contacts</ui:define>
    <ui:define name="pageHeader">Contacts</ui:define>
    <ui:define name="body">
        <p />
        <h:form style="display: inline;">
            <table>
                <!-- The input tag is defined on a Faceles composite component at {webroot}/resources/jdf/input.xhtml-->
                <jdf:input name="id" label="Id" value="#{contactController.contact.id}" readonly="true" rendered="#{contactController.contactManaged}"/>
                <jdf:input name="name" label="Name" value="#{contactController.contact.name}" required="true" />
                <jdf:input name="email" label="eMail" value="#{contactController.contact.email}" required="true" readonly="#{contactController.contactManaged}" />
                <jdf:input name="phone" label="Phone Number" value="#{contactController.contact.phoneNumber}" />
            </table>
            <h:commandButton action="#{contactController.save()}" value="Save" />
        </h:form>
        <h:form style="display: inline;">
            <h:commandButton action="#{contactController.remove(contactController.contact)}" value="Remove" rendered="#{contactController.contactManaged}" onclick="return confirm('Do you want to remove this record?');"/>
            <h:commandButton action="#{contactController.newContact()}" value="New Contact"/>
        </h:form>

        <ul style="text-align: left; text-align: justify;">
            <li><b>To insert a new contact:</b> Click the <i>New Contact</i> button, complete the form fields, and then click the <i>Save</i> button. Notice that both the <i>All Contacts</i> and <i>Audit Records</i> tables are updated.</li>  
            <li><b>To modify an existing contact:</b> Find the name in the <i>All Contacts</i> table and click the <i>Select for edit</i> button. Modify the data and then click the <i>Save</i> button. Notice that the <i>Audit Records</i> table is updated with the new contact data.</li>
            <li><b>To remove a contact:</b> Find the name in the <i>All Contacts</i> table and click the <i>Remove</i> button. Notice that the <i>Audit Records</i> table is updated with the new contact data.</li>
        </ul>
        <p>*Note: To fire the UPDATE audit, you must change one of the contact fields</p>
        
        <hr />
        
        <h2>All Contacts</h2>
        <h:form>
            <h:dataTable value="#{contactController.allContacts}" var="varContact" width="100%">
                <h:column>
                    <f:facet name="header">Id</f:facet>
                #{varContact.id}
            </h:column>
                <h:column>
                    <f:facet name="header">Name</f:facet>
                #{varContact.name}
            </h:column>
                <h:column>
                    <f:facet name="header">email</f:facet>
                #{varContact.email}
            </h:column>
                <h:column>
                    <f:facet name="header">Phone Number</f:facet>
                #{varContact.phoneNumber}
            </h:column>
                <h:column>
                    <f:facet name="header">Operations</f:facet>
                    <h:commandButton action="#{contactController.selectForEdit(varContact)}" value="Select for edit" />
                    <h:commandButton action="#{contactController.remove(varContact)}" value="Remove" onclick="return confirm('Do you want to remove this record?');" />
                </h:column>
            </h:dataTable>
        </h:form>
        <p />
        <hr />
        <h2>Audit Records</h2>
        <h:outputText value="No audit records found..."  rendered="#{empty contactController.auditRecords}"/>
        <h:dataTable value="#{contactController.auditRecords}" var="varAudit" width="100%" rendered="#{not empty contactController.auditRecords}">
            <h:column>
                <f:facet name="header">Contact e-Mail</f:facet>
                #{varAudit.contactEmail}
            </h:column>
            <h:column>
                <f:facet name="header">Contact Name</f:facet>
                #{varAudit.contactName}
            </h:column>
            <h:column>
                <f:facet name="header">Contact Phone</f:facet>
                #{varAudit.contactPhone}
            </h:column>
            <h:column>
                <f:facet name="header">Date/Time</f:facet>
                <h:outputText value="#{varAudit.dateTime}">
                    <!-- Converts the data to String using the specified format and the TimeZone that was produced -->
                    <f:convertDateTime type="both" timeZone="#{applicationTimezone}" />
                </h:outputText>
            </h:column>
            <h:column>
                <f:facet name="header">Operation</f:facet>
                #{varAudit.operation}
            </h:column>
        </h:dataTable>
        <p />
    </ui:define>

    <ui:define name="footer">
        <!-- Display the current conversation -->
        <h:outputText value="#{contactController.conversationNumber}" />
    </ui:define>
</ui:composition>
</html>

coursework-cbsd/deltaspike-beanmanagerprovider/src/main/webapp/template.xhtml
<!--
    JBoss, Home of Professional Open Source
    Copyright 2014, Red Hat, Inc. and/or its affiliates, and individual
    contributors by the @authors tag. See the copyright.txt in the
    distribution for a full listing of individual contributors.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets">
		<head>
		<title><ui:insert name="pageTitle">Page Title</ui:insert></title>
		<style type="text/css">
			body {
				  font-family: Verdana, Arial, Helvetica, sans-serif;
				  font-size: 14px;
			}
			.header {
				  font-family: Verdana, Arial, Helvetica, sans-serif;
				  font-size: 18px;
			}
			.bottom {
				  font-family: Verdana, Arial, Helvetica, sans-serif;
				  font-size: 9px;
				  text-align: center;
				  vertical-align: middle;
				  color: #8E969D;
			}
            tr {
                text-align: left;
            }
		</style>
		</head>

<body bgcolor="#ffffff">
<table style="border:1px solid #CAD6E0"  align="center" cellpadding="0" cellspacing="0" border="0" width="1000">
<tbody>

	<tr>
		<td class="header" height="42" align="center" valign="middle" width="100%" bgcolor="#E4EBEB">
			<ui:insert name="pageHeader">Page Header</ui:insert>
		</td>
	</tr>
	<tr>
		<td height="1" width="100%" bgcolor="#CAD6E0"></td>
	</tr>	

	<tr>
		<td width="100%"  colspan="2">
			<table width="100%" style="height:150px" align="left" cellpadding="0" cellspacing="0" border="0">
			<tbody>
				<tr>
					<td width="100%" valign="middle">
                        <h:messages  globalOnly="true"/>
    					<ui:insert name="body">Page Body</ui:insert>
					</td>
				</tr>
			</tbody>
			</table>
		</td>
	</tr>	
	
	<tr>
		<td colspan="2"  valign="bottom" height="1" width="100%" bgcolor="#CAD6E0">
            <ui:insert name="footer"/>
        </td>
	</tr>
</tbody>
</table>
</body>
		
</html>